### ISSUE TITLE
Code release?

### ISSUE THREAD

**Issue by ZhangYang-UCAS** [qinghew/StableIdentity#1]
good work！！！
your project looks very interesting, do you have a date for it's release?

**Comment by qinghew** [comment]
If everything goes well, we will update within a month.

**Comment by imperator-maximus** [comment]
I am wondering if you have used InsightFace for training? So your result could be used for non-commercial purpose only like FaceID or InstantID.

**Comment by qinghew** [comment]
> I am wondering if you have used InsightFace for training? So your result could be used for non-commercial purpose only like FaceID or InstantID.

The employed face recognition encoder is from https://huggingface.co/jayanta/vit-base-patch16-224-in21k-face-recognition.

**Comment by qinghew** [comment]
> good work！！！ your project looks very interesting, do you have a date for it's release?

Welcome to try with our codes:)
