### ISSUE TITLE
Only train a emb model?

### ISSUE THREAD

**Issue by scorpioliu** [qinghew/StableIdentity#4]
Does this release code only train emb models for faces?

**Comment by qinghew** [comment]
Yes, our methods are proposed for faces.

**Comment by qinghew** [comment]
We train the MLPs mentioned in our paper and only save identity embeddings for easier inference. If you want to save the MLPs, you could uncomment the [codes](https://github.com/qinghew/StableIdentity/blob/0d7a1285fb05399907da5e6b1ce73eb7efad12f8/models/embedding_manager.py#L110).
