### ISSUE TITLE
How can I obtain sufficiently good intermediate representations as you provided tmp.pt?

### ISSUE THREAD

**Issue by murphytju** [qinghew/StableIdentity#6]
How can I obtain sufficiently good intermediate representations as you provided tmp.pt? I use your provided face images and train for 450 iters, but results is not very good. When I use faces from some other datasets, the generated videos are unrelated to them. I suspect it's an issue with the first stage of my training.
![01247](https://github.com/qinghew/StableIdentity/assets/82270941/d39fdb70-3588-4012-8275-f8e18273b5e2)

https://github.com/qinghew/StableIdentity/assets/82270941/53660dcb-1da7-4c11-a838-b5ccfa1a5a79

**Comment by qinghew** [comment]
I just fix a bug of my "[README.md](https://github.com/qinghew/StableIdentity/blob/main/README.md)". The base model is [SD2.1-512](https://huggingface.co/stabilityai/stable-diffusion-2-1-base). So sorry for this bug.

**Comment by murphytju** [comment]
oh my god :) Thanks!
