### ISSUE TITLE
Support for Larger Diffusion Models

### ISSUE THREAD

**Issue by DELTA-DoubleWise** [qinghew/StableIdentity#7]
Hi! Thanks for sharing this inspiring work! Have you tried to implement the same structure on larger diffusion models like StableDiffusionXL? It seems that the same method should work well on other models as well.

**Comment by qinghew** [comment]
Empirically, this method could be adapted to larger diffusion models, but we don't have this plan. Feel free to follow our upcoming new work, which will be available on arxiv in two weeks.
