### ISSUE TITLE
where is test_emb_path

### ISSUE THREAD

**Issue by Oguzhanercan** [qinghew/StableIdentity#9]
Hi, I believe that test_emb_path is the embedding of the face image. But how can I extract the relative embedding, can you share the code snippet of it? Also, if you have, can you share the preprocessing step for face image like alignment etc.?

**Comment by qinghew** [comment]
1. "Train for a single test image" in README will produce the embedding for the face image.
2. preprocessing step for face image like alignment: [FFHQ-Alignment](https://github.com/happy-jihye/FFHQ-Alignment)

**Comment by Oguzhanercan** [comment]
Sorry, I thought that it was training free method, so skiped the train part.
